trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  displayName: 'Copy files to $(build.artifactstagingdirectory)/Templates'
  inputs:
    SourceFolder: 'deployment'
    Contents: '*.json'
    TargetFolder: '$(build.artifactstagingdirectory)/Templates'

- task: Npm@1
  inputs:
    command: 'custom'
    verbose: false
    customCommand: 'install --production'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourceDirectory)'
    includeRootFolder: false


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'







